### ISSUE TITLE
Possible to do an update without overwriting other fields?

### ISSUE THREAD

**Issue by danmelnick** [elasticsales/closeio-api#17]
Example: a Lead has 3 custom fields, I want to update one of them. If I sent an update with only that one field, it seems to null out the other 2 fields.

Do I really need to do a round trip to get existing values, merge in my change, then send the update?

**Comment by danmelnick** [comment]
Sorry, found my answer in the docs. I'd submit that this is an odd way for the API to behave but I can see the path for me to do what I need.

**Comment by philfreo** [comment]
For anyone else looking, the solution for updating a single custom field is to do a `PUT /api/v1/lead/` with the JSON key `custom.my field name` instead of posting the custom dict.
