### ISSUE TITLE
Script to bulk update leads from CSV

### ISSUE THREAD

**Issue by philfreo** [elasticsales/closeio-api#19]
We need a script that takes a CSV file with some or all of these columns:

- lead_id
- company
- description
- url
- status
- contact1_name
- contact1_title
- contact1_phone1
- contact1_email1
- contact1_url1
- custom.foo bar ("foo bar" can be _any_ valid custom field that already exists)

The basic idea is that the script should help you *bulk edit* leads in Close.io and bulk-add contacts to existing leads. For lead-specific fields (description, url, status, custom fields) it will _update_ the lead and it will always add contacts to the leads.

- Have a --confirmed flag and the script should be read-only for testing until this is set. See https://github.com/elasticsales/closeio-api/blob/master/scripts/move_custom_field_to_contact_info.py for an example but feel free to improve it 
- Make sure the script is well documented with command line instructions. Assume the user isn't sure how it works :)
- Assume that the user running the script will make a mistake with the headers so put in some nice checks to warn them if the script has unrecognized headers and make them correct it before continuing.
- Use the custom fields endpoint to make sure that any custom fields listed are valid
- Per row there can be up to 9 contacts (e.g. contact9_name) and each contact can have up to 9 phone numbers (e.g. contact5_phone3), emails, and urls.
- Require that either lead_id or company name must be there 
- Some rows may not have all the fields filled out. Some rows may be trying to add 3 contacts some rows may be trying to add 1 contact.
- Loop through each CSV row:
 - Lookup to find an existing lead to edit. IF lead_id is a column in the CSV then _only_ edit based on the lead_id. 
 - If lead_id doesn't exist then for each row look up the lead to update based on the 'company' field. Use the ?query param with a "company:" prefix to do this. If you find multiple leads you should print a warning about this but if its in confirmed mode (see below) then just pick the first lead.
 - By default you'll create new leads if you don't find a lead from the lead_id or company name lookup. But have a --disable-create option to turn this off.
- Have a nice printout of which rows were rejected due to 400 errors / bad data / validation errors. The user can fix those rows and then re-run if they want.

@congocongo Can you work on this asap? If your trial account is expired just shoot an email to support@close.io asking for us to extend it b/c you're working on this script. Let me know if anything needs any clarification :)

**Comment by congocongo** [comment]
yes, I accepted.

**Comment by philfreo** [comment]
Hey @congocongo Let's add a few new fields -- this time to create Opportunities if the fields are present

opportunity1_note
opportunity1_value -- in cents
opportunity1_value_period -- will have a value like `one_time` or `monthly`
opportunity1_confidence 
opportunity1_status

where "1" could be 1-9 to create multiple

**Comment by philfreo** [comment]
ANNNND another one. This time to POST notes to a lead.

note1

where "1" could be 1-9 to create multiple
