### ISSUE TITLE
Script to bulk update the country code of all addresses in leads matching a certain search query

### ISSUE THREAD

**Issue by philfreo** [elasticsales/closeio-api#21]
bulk_update_address_countries.py

inputs:
- api key
- old country code
- new country code
- leads search query (defaults to `* sort:created` if none) -- can be coded in script since it's hard to pass complicated queries (e.g. quotes) to cli args

python cli script that takes these items as inputs. it should loop through each lead in the given search query, and if there are any addresses on that lead with the `old country code` then it should update the address with the new country code

Would also like a read-only preview mode of what will happen and then a --confirmed flag

@congocongo Can you work on this one after the other script?

**Comment by thomasst** [comment]
@congocongo When do you think the script will be ready?

**Comment by congocongo** [comment]
I did already.

**Comment by thomasst** [comment]
Thanks! Didn't see it since it wasn't referenced here

**Comment by philfreo** [comment]
Handled in #22
