### ISSUE TITLE
Script to assign tasks/opportunities from one user to another user

### ISSUE THREAD

**Issue by thomasst** [elasticsales/closeio-api#26]
user_reassign.py

Input:
* API key
* --confirmed flag
* --from-user-id
* --to-user-id
* `--tasks`: if given, update tasks
* `--opportunities`: if given, update opportunities

Either --tasks or --opportunities (or both) should be specified 

What the script should do:
* Assign all tasks and/or opportunities that are assigned from one user to another

**Comment by philfreo** [comment]
@congocongo Can you work on this one next?

**Comment by congocongo** [comment]
yes, accepted
