### ISSUE TITLE
Unable to save opportunities

### ISSUE THREAD

**Issue by wundo** [elasticsales/closeio-api#9]
Try:
```php
  $opportunity = new Opportunity();
  $opportunity->setConfidence("50");

  $lead->setOpportunities(array($opportunity));
  $response = $leadsApi->addLead($lead);
```

Nothing happens :(

**Comment by philfreo** [comment]
Which client library are you using?

**Comment by wundo** [comment]
PHP, sorry I figured out I posted in the wrong repo...

**Comment by wundo** [comment]
https://github.com/loopline-systems/closeio-api-wrapper/tree/master/src/LooplineSystems/CloseIoApiWrapper
